version: "3"
networks:
  salle.net:
    driver: bridge

services:

  web:
    build:
      dockerfile: docker/web
    command: ["node", "/app/.output/server/index.mjs"]
    working_dir: /app
    networks:
      - salle.net
    environment:
      - NODE_ENV=production
      - PORT=3000

  api:
    image: 'node:alpine'
    command: sh -c "npm i && npm run start"
    volumes:
      - ./api:/app
    working_dir: /app
    networks:
      - salle.net
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SECRET_KEY=${SECRET_KEY:-secret}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-sallemagne}
    depends_on:
      - db

  db:
    image: mariadb:10.4
    container_name: mariadb
    networks:
      - salle.net
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-sallemagne}
      MYSQL_USER: ${MYSQL_USER:-salle}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    volumes:
      - ./api/sql/init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    command: php -S 0.0.0.0:8080 -t /var/www/html
    container_name: adminer
    networks:
      - salle.net


  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certificat:/etc/nginx/certificat
    networks:
      - salle.net
    ports:
      - '32498:2498'
      - "32496:2496"
      - "32497:2497"
      - '32495:2495'
    depends_on:
      - web
      - api
      - db
      - adminer
