name: salle_magne
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-275.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  image_picker: ^1.0.7
  table_calendar: ^3.0.8
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true
